Add controllers
evilaks/java-shareit pull request #1
Opened 2023-03-23 14:02 UTC by evilaks

Добавлена логика работы с пользователями
Добавлена логика работы с вещами

2023-03-28 21:14 UTC, andrew-larkin requested changes
Привет! Отличный старт, код написан архитектурно корректно. 2 небольших изменения и будем готовы двигаться дальше.

2023-03-28 21:14 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto addItem(@RequestHeader(value = "X-Sharer-User-Id") Long ownerId, @RequestBody ItemDto itemDto) {
давай для этого приложения для методов контроллеров будем использовать класс-обертку ResponseEntity - он возвращает не только json, но и http-статус. Будет выглядеть как-то так: return ResponseEntity.ok().body(itemService.add(ownerId, itemDto));

2023-03-28 21:14 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoMapper.java
> +public class ItemDtoMapper {
для этого приложения также давай внедрим библиотеку mapStruct - она используется практически на всех реальных проектах, поэтому будет полезно ее изучить. Она небольшая, на самом деле, там разобраться - минут 10

2023-03-28 21:14 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long ownerId;
сюда можно вставить User

2023-03-29 18:10 UTC, evilaks commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto addItem(@RequestHeader(value = "X-Sharer-User-Id") Long ownerId, @RequestBody ItemDto itemDto) {
Добавил

2023-03-29 18:11 UTC, evilaks commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long ownerId;
Вставил

2023-03-29 18:11 UTC, evilaks commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoMapper.java
> +public class ItemDtoMapper {
Добавил библиотеку, но развалились тесты гитлаба. При этом локально всё работает корректно.

2023-03-29 18:13 UTC, evilaks commented
Всё сделал, но после добавления mapStruct развалились тесты гитлаба. При этом локально всё работает.

2023-03-31 07:12 UTC, merged