Add item requests
evilaks/java-shareit pull request #3
Opened 2023-05-01 18:24 UTC by evilaks

2023-05-03 21:34 UTC, andrew-larkin requested changes
Привет! Отлично, очень качественная реализация и тесты написаны действительно хорошо. Остается буквально в паре мест дополнить и приложение будет готово.

2023-05-03 21:34 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      @DeleteMapping("/{itemId}")
если сервис возвращает void, мы можем использовать ResponseEntity c типом Void

2023-05-03 21:34 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    POST /requests — добавить новый запрос вещи. Основная часть запроса — текст запроса, где пользователь описывает,
такой большой блок комментария стоит удалить. либо оформить как документацию с помощью спец разметки. но лучше просто удалить)

2023-05-03 21:34 UTC, andrew-larkin commented on src/test/java/ru/practicum/shareit/booking/BookingControllerIntegrationTest.java
> +        @Sql(executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD, scripts = "classpath:test-data.sql"),
отличная идея, очень часто в тестах используются sql-скрипты. а чтобы не забирать их из папки с ресурсами для основного кода приложения, мы можем создать отдельную папку ресурсов для папки с тестами (у нее даже свой значок есть), попробуй

2023-05-04 06:30 UTC, evilaks commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
>      @DeleteMapping("/{itemId}")
готово

2023-05-04 06:30 UTC, evilaks commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    POST /requests — добавить новый запрос вещи. Основная часть запроса — текст запроса, где пользователь описывает,
удалил)

2023-05-04 06:35 UTC, evilaks commented on src/test/java/ru/practicum/shareit/booking/BookingControllerIntegrationTest.java
> +        @Sql(executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD, scripts = "classpath:test-data.sql"),
перенёс)

2023-05-04 18:15 UTC, merged